### ISSUE TITLE
Should i release it?

### ISSUE THREAD

**Issue by honghongleong** [honghongleong/Vrv-Downloader#1]
Should I release it?

**Comment by Oujiii** [comment]
Yes. If possible, ported to Linux too. What are the possible quality for the downloaded video? You can also add a feature to login to the website if the video is premium or require a login.

**Comment by honghongleong** [comment]
Possible quality are 240p,480p,640p(if i remember correctly)1080p and best.I’ve test with crunchyroll and cartoon hangover.Those who require premium account such as curiositystream,hidive ect... There’s a require premium? Option where users could input their premium account login but I can’t test if it really works since I don’t live in the us nor have a premium account.

**Comment by Oujiii** [comment]
Oh, I see. I think you should release anyway and we could test it. I think Hidive requires a premium account. Also, videos from newer series on Crunchyroll also require if I'm not mistaken.
Try to download Dr. STONE episode 16

**Comment by honghongleong** [comment]
I'll release it when i'm back in my country.
