### ISSUE TITLE
How do you decrypt vrv video links?

### ISSUE THREAD

**Issue by RootEncrypter** [honghongleong/Vrv-Downloader#13]
I am able to get the vrv Video stream links but how do you decrypt them? I have couple of premium accounts for vrv , If possible we could discuss and i could help you with premium accounts!

**Comment by honghongleong** [comment]
Hello There!
I appreciate you wanting to help out.As for decrypting the video,I'm assuming your talking about the Opening'+crypto+https://vrv.co...' If It's that they are handled by youtube-dl.
![image](https://user-images.githubusercontent.com/50738510/99060635-46c03800-25db-11eb-8f40-661c89efb187.png)

**Comment by RootEncrypter** [comment]
```I am able to get the link manually too , but i dont no how to decrypt it so i can download the mp4.
```


![image](https://user-images.githubusercontent.com/62509239/99061990-4b2f2580-25c8-11eb-9506-842be858f743.png)

**Comment by honghongleong** [comment]
Sorry I'm not sure too since it's all done by youtube-dl.

**Comment by RootEncrypter** [comment]
anyways i wish to make a pyhton bot, which takes url as input and sends a mp4 link which has the entire episode . Is it possible to implement it for a bot ? @honghongleong

**Comment by honghongleong** [comment]
> anyways i wish to make a pyhton bot, which takes url as input and sends a mp4 link which has the entire episode . Is it possible to implement it for a bot ? @honghongleong 

It should be possible.

**Comment by death-angel-141** [comment]
@RootEncrypter it actually download parts by parts and then merges into a single mp4 file, hope that helps
