### ISSUE TITLE
Cant Start It up

### ISSUE THREAD

**Issue by HealthyAnimeKid** [honghongleong/Vrv-Downloader#14]
Keeps saying it needs to install Youtube-dl but then just shows the download bar and dosint do anything does it take a super long time or am i doing something wrong?
![Capture](https://user-images.githubusercontent.com/71133898/108391164-6b7e0a00-71df-11eb-98f5-c66e26ee5f8a.PNG)

**Comment by honghongleong** [comment]
Place the contents inside the zip under C:\ProgramData

[Link](https://drive.google.com/file/d/1y-9W_nosTDna82Bbqr7lP6obZtuZXc23/view?usp=sharing)
