### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by darkhelmet2016** [honghongleong/Vrv-Downloader#4]
Get an error running the program that says dependencies seem corrupted or missing.

**Comment by honghongleong** [comment]
Sorry about the dependencies.It seems to have some error getting it from the github I would work on it later.Mean while download the zip and extract it to C:\ProgramData\Vrv-DL it should work. [https://drive.google.com/file/d/12198oocWHJNG9w-2gVOti53hRLDkicbX/view?usp=sharing](url)

**Comment by darkhelmet2016** [comment]
Thanks. The file says permission denied.

**Comment by honghongleong** [comment]
> Thanks. The file says permission denied.

Try this.
https://drive.google.com/drive/folders/1H-FO4HfxaGuPmH9mELxZPbpCcPHMmp19?usp=sharing
