### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by honghongleong** [honghongleong/Vrv-Downloader#7]
Until now I have not been able to download anything, it always comes out that I should check if the link is correct.

_Originally posted by @Lito150 in https://github.com/honghongleong/Vrv-Downloader/issues/3#issuecomment-664004062_

**Comment by honghongleong** [comment]
Use a vpn if you're outside the United States and the downloader could only download episode one at a time not including premium(unless you have a premium account).

**Comment by honghongleong** [comment]
If there are no other issue I'll close this.

**Comment by Oujiii** [comment]
I have a premium account and tried downloading two different first episodes from two different series. Bungou Stray Dogs and Date A Live, both failed with the URL error. I'm using a VPN and I know it's working because I can access the website. Any thoughts?
