### ISSUE TITLE
Download/Premium acc issue.

### ISSUE THREAD

**Issue by honghongleong** [honghongleong/Vrv-Downloader#8]
I have a premium account and tried downloading two different first episodes from two different series. Bungou Stray Dogs and Date A Live, both failed with the URL error. I'm using a VPN and I know it's working because I can access the website. Any thoughts?

_Originally posted by @Oujiii in https://github.com/honghongleong/Vrv-Downloader/issues/7#issuecomment-667777589_

**Comment by honghongleong** [comment]
You copied the episode link and not the series name i assume?🤔

**Comment by Oujiii** [comment]
Yes, isn't that how it is supposed to work? Since you mentioned there is no way to download a whole series, I just copied the link for the specific episode.

**Comment by honghongleong** [comment]
> Yes, isn't that how it is supposed to work? Since you mentioned there is no way to download a whole series, I just copied the link for the specific episode.

That's how it's supposed to work(for now)I'll try to see what can i do when i reach home.Are you downloading from Hidive or just crunchyroll premium episode?

**Comment by Oujiii** [comment]
The episodes were from Crunchyroll. I'm not sure if they were premium only. I tried the first episode of Date a Live without the "premium account required" toggle on and had the same error. So I thought that using my premium account could help, but it didn't.

I appreciate your help!

**Comment by Oujiii** [comment]
Just an update. I was able to access the episode without premium. [This is the link for it](https://vrv.co/watch/GR9VPG346/Date-A-Live:April-1x)

Still can't download.

**Comment by Oujiii** [comment]
I tried with two VPN services. Windscribe and VPN Unlimited. I tried in two servers in Miami, FL and it didn't work, same error. I can access and watch just fine via browser. Tried without using my account this time

**Comment by honghongleong** [comment]
> I tried with two VPN services. Windscribe and VPN Unlimited. I tried in two servers in Miami, FL and it didn't work, same error. I can access and watch just fine via browser. Tried without using my account this time

I'm using hotspot shield no problem downloading which is weird :/

**Comment by honghongleong** [comment]
@Oujiii Could you help me test this new fix real quick?Just replace the exe in your folder
[Vrv-Downloader.zip](https://github.com/honghongleong/Vrv-Downloader/files/5016560/Vrv-Downloader.zip)

**Comment by Oujiii** [comment]
Okay, I tested with Hotspotshield before seeing your latest reply and it didn't work. Replaced with the binary you just provided and now I'm downloading using Windscribe without any issues.

**Comment by honghongleong** [comment]
Thanks for the reply!
It seemed to be some issues about python dealing with expired certificates.Herd Python 3.8.2 has newer openssl but I haven't tried it due to limited time.
I'll push a new release soon,thanks a lot for your help!Appreciated!

**Comment by Oujiii** [comment]
I appreciate your help and fast reply as well. Do you have any ideia on when you might implement whole series download or batch download?

Thank you again!

**Comment by honghongleong** [comment]
> I appreciate your help and fast reply as well. Do you have any ideia on when you might implement whole series download or batch download?
> 
> Thank you again!

About this I'll have to find a way to solve as the problem is with the progress window.As referenced in #3 
`var progress = step.TotalMilliseconds / totalDuration.Value.TotalMilliseconds;
data.Progress.CurrentTask.Progress = progress;`

**Comment by honghongleong** [comment]
I'll now close this Issue,Thanks a lot for your help!
